export const ADD_BUDGET_ITEM = 'ADD_BUDGET_ITEM';
export const DELETE_BUDGET_ITEM = 'DELETE_BUDGET_ITEM';
export const CHANGE_CURRENCY_TYPE = 'CHANGE_CURRENCY_TYPE';
export const CHANGE_CURRENCY_RATE = 'CHANGE_CURRENCY_RATE';
export const DISABLE_FILTER = 'DISABLE_FILTER';
